{{- if .Values.kiali.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: kiali
  labels:
    {{- include "bigbang.istioInjectionLabel" . | nindent 4 }}
    app.kubernetes.io/name: kiali
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" . | nindent 4}}
{{- end }}