{{- if and (or .Values.eckoperator.enabled .Values.logging.enabled .Values.clusterAuditor.enabled) (eq .Values.logging.engine "efk") }}
{{- include "values-secret" (dict "root" $ "package" .Values.eckoperator "name" "eck-operator" "defaults" (include "bigbang.defaults.eck-operator" .)) }}
{{- end }}

{{- define "bigbang.defaults.eck-operator" -}}
license:
  trial: {{ .Values.ek.license.trial }}
  keyJSON: |
    {{ .Values.ek.license.keyJSON | nindent 4 }}

podAnnotations:
  sidecar.istio.io/inject: "true"
  traffic.sidecar.istio.io/includeInboundPorts: "*"
  traffic.sidecar.istio.io/excludeInboundPorts: "9443"

openshift: {{ .Values.openshift }}

networkPolicies:
  enabled: {{ .Values.networkPolicies.enabled }}
  controlPlaneCidr: {{ .Values.networkPolicies.controlPlaneCidr }}

imagePullSecrets:
  - name: private-registry
{{- end -}}
