include:
  - project: 'platform-one/big-bang/pipeline-templates/pipeline-templates'
    ref: enable-changed-packages
    file: '/pipelines/bigbang.yaml'

variables:
  PIPELINE_REPO_BRANCH: enable-changed-packages
