include:
  - project: 'platform-one/big-bang/pipeline-templates/pipeline-templates'
    ref: k3d-multi-node-p2
    file: '/pipelines/bigbang.yaml'
variables:
  PIPELINE_REPO_BRANCH: 'k3d-multi-node-p2' 
  MULTI_NODE: "true"
