include:
  - project: 'platform-one/big-bang/pipeline-templates/pipeline-templates'
    ref: eks-support
    file: '/pipelines/bigbang.yaml'
variables:
  PIPELINE_REPO_BRANCH: 'eks-support'
  DEBUG_ENABLED: "true"


