{{- if and (and (not .Values.offline) (or .Values.logging.enabled .Values.clusterAuditor.enabled)) (eq .Values.logging.engine "efk") }}
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: elasticsearch-kibana
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: logging
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" . | nindent 4}}
spec:
  interval: {{ .Values.flux.interval }}
  url: {{ .Values.ek.git.repo }}
  ref:
    {{- include "validRef" .Values.ek.git | nindent 4 }}
  {{ include "gitIgnore" . }}
  {{- include "gitCreds" . | nindent 2 }}
{{- end }}
