{{- $fluxSettingsNeuvector := merge .Values.neuvector.flux .Values.flux -}}
{{- if .Values.neuvector.enabled }}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: neuvector
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: neuvector
    app.kubernetes.io/component: "security"
    {{- include "commonLabels" . | nindent 4}}
spec:
  targetNamespace: neuvector
  chart:
    spec:
      chart: {{ .Values.neuvector.git.path }}
      interval: 5m
      sourceRef:
        kind: GitRepository
        name: neuvector
        namespace: {{ .Release.Namespace }}

  {{- toYaml $fluxSettingsTwistlock | nindent 2 }}
  
  {{- if .Values.neuvector.postRenderers }}
  postRenderers:
  {{ toYaml .Values.neuvector.postRenderers | nindent 4 }}
  {{- end }}
  valuesFrom:
    - name: {{ .Release.Name }}-neuvector-values
      kind: Secret
      valuesKey: "common"
    - name: {{ .Release.Name }}-neuvector-values
      kind: Secret
      valuesKey: "defaults"
    - name: {{ .Release.Name }}-neuvector-values
      kind: Secret
      valuesKey: "overlays"

  # TODO: DRY this up
  {{- if or .Values.gatekeeper.enabled .Values.istio.enabled }}
  dependsOn:
    {{- if .Values.gatekeeper.enabled }}
    - name: gatekeeper
      namespace: {{ .Release.Namespace }}
    {{- end }}
    {{- if .Values.istio.enabled }}
    - name: istio
      namespace: {{ .Release.Namespace }}
    {{- end }}
    {{- if .Values.monitoring.enabled }}
    - name: monitoring
      namespace: {{ .Release.Namespace }}
    {{- end }}
  {{- end }}
{{- end }}
