{{- /* Used for creating secret for the package's HelmRelease */ -}}

{{- $bb_domain := .Values.domain }}
{{- $bb_istio_enabled := .Values.istio.enabled }}
{{- $bb_monitoring_enabled := .Values.monitoring.enabled }}
{{- $bb_gatekeeper_enabled := .Values.gatekeeper.enabled }}

{{- range $pkg, $vals := .Values.packages -}}
{{- if (dig "enabled" true $vals) -}}
{{- $pkg = include "resourceName" $pkg -}}
apiVersion: v1
kind: Secret
metadata:
  name: bigbang-values
  namespace: {{ dig "namespace" "name" $pkg $vals }}
  labels:
    {{- include "commonLabels" $ | nindent 4 }}
type: Opaque
stringData:
  values.yaml: |
    bb_domain: {{ $bb_domain }}
    bb_istio:
      enabled: {{ $bb_istio_enabled }}
    bb_monitoring:
      enabled: {{ $bb_monitoring_enabled }}
    bb_gatekeeper:
      enabled: {{ $bb_gatekeeper_enabled }}  
---
{{ end -}}
{{- end -}}