{{- if .Values.monitoring.sso.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.monitoring.sso.namespace }}
  labels:
    istio-injection: enabled

{{- if and (ne .Values.registryCredentials.username "") (ne .Values.registryCredentials.password "") }}
---
apiVersion: v1
kind: Secret
metadata:
  name: private-registry
  namespace: {{ .Values.monitoring.sso.namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
{{- end }}