{{- if .Values.jaeger.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: jaeger
  labels:
    {{- include "bigbang.istioInjectionLabel" . | nindent 4 }}
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" . | nindent 4}}
{{- end }}