{{ $enabled := .Values.istio.enable | default false }}
{{- range $values := .Values.istio.controlplanes }}
{{ if and ($values.enabled) (eq $enabled false) }}{{ $enabled = true }}{{- end }}
{{- end }}

{{- if and $enabled $.Values.openshift (include "imagePullSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: private-registry
  namespace: kube-system
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
